### PR TITLE
Add AS5600

### PR DESCRIPTION
**Pull request by bwestley**
[https://ams-osram.com/products/sensors/position-sensors/ams-as5600-position-sensor](Manufacturer)
Added schematic symbol:
image
Datasheet ref:
image
The master branch is protected so I had to create a new branch to make this change.

### CODE REVIEW

**Comment by bwestley** [comment]
If the library change can't be merged, try importing the symbol yourself:
[as5600.zip](https://github.com/user-attachments/files/17157133/as5600.zip)

**Comment by OcelotEmpire** [comment]
Make sure you link the datasheet in the symbol:
Symbol Editor -> Filter: AS5600 -> Symbol Properties (triangle with gear on the top bar) -> datasheet -> paste in the link
Also just a nitpick but we usually make the symbol's origin in the center-ish instead of the top left corner

**Review by OcelotEmpire — CHANGES_REQUESTED** [review]
I guess I should post this as a review instead of a comment...

Make sure you link the datasheet in the symbol:
Symbol Editor -> Filter: AS5600 -> Symbol Properties (triangle with gear on the top bar) -> datasheet -> paste in the link
Also just a nitpick but we usually make the symbol's origin in the center-ish instead of the top left corner

**Review by OcelotEmpire — APPROVED** [review]
looks good to me

**Pull request merged**
